title: Saraf Ray
tagline: Project Portfolio
logo: "/images/newheadshot.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Hello, my name is Saraf!  
  <br><br>
  I am a software engineer from Brooklyn
  <br><br>
  I am open to full time work!
  <br>
  Email me at <a href="mailto:sarafiskray@gmail.com">sarafiskray@gmail.com</a>
  <br><br>
  <a href="https://www.linkedin.com/in/saraf-ray-3a181814a/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://github.com/sarafiskray">View My GitHub Profile</a>
  
theme: jekyll-theme-minimal

