title: Saraf Ray # your name (or website title) here
logo: "/images/headshot.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Hello, I am a software engineer and recent graduate from the University of Vermont. Experience with REST API design, database management, 
  front-end web development, and more.  I am also trilingual with a high level of communication in English, Spanish, and Bengali.  Always eager to learn.
  <br><br>
  I am currently open to full time work!
  <br>
  Email me at sarafiskray@gmail.com
  <br><br>
  <a href="https://www.linkedin.com/in/saraf-ray-3a181814a/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://github.com/sarafiskray">View My GitHub Profile</a>
  
theme: jekyll-theme-minimal

