title: Saraf Ray
logo: "/images/newheadshot.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  <p style="font-size: large">
  Hello, my name is Saraf!  
  <br><br>
  I am a software engineer from Brooklyn.
  <br><br>
  <a href="https://sarafiskray.github.io/aboutme">About Me</a></p>
  <br><br>
  <a href="https://www.linkedin.com/in/saraf-ray-3a181814a/"> <i class="fa fa-linkedin fa-3x" aria-hidden="true" style="padding-right:25px;"></i> </a> <a href="https://github.com/sarafiskray"> <i class="fa fa-github fa-3x" aria-hidden="true"></i> </a>
  
theme: jekyll-theme-minimal

 