title: Saraf Ray # your name (or website title) here
logo: "/images/headshot.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Hello, I am Saraf, a software engineer and recent graduate from the University of Vermont with a demonstrated history of developing a variety of software solutions. 
  Experience with REST API design, database management, front-end web development, and more.  I am also trilingual with a high level of communication in English, Spanish, and Bengali.
  <br><br>
  I am currently open to full time work!
  <br><br>
  <a href="https://www.linkedin.com/in/saraf-ray-3a181814a/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
