title: Saraf Ray # your name (or website title) here
logo: "/images/headshot.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Hello, my name is Saraf! 
  <br>
  I am a software engineer, raised in Brooklyn and recently graduated from the University of Vermont.  I enjoy learning new concepts and building software that has a positive impact on people's lives. 
  I have experience with REST API design, database management, front-end web development, and more. Currently I am working on a project using Rails and React.
  <br>
  Outside of software, some of my other interests include hiking, biking, cooking and watching sports.  I am also trilingual in English, Spanish, and Bengali.
  <br>
  I am open to full time work!
  <br>
  Email me at <a href="mailto:sarafiskray@gmail.com">sarafiskray@gmail.com</a>
  <br><br>
  <a href="https://www.linkedin.com/in/saraf-ray-3a181814a/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://github.com/sarafiskray">View My GitHub Profile</a>
  
theme: jekyll-theme-minimal

